# Generated by Django 6.0 on 2025-12-13 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(help_text='Número de matrícula o folio del alumno', max_length=20, unique=True, verbose_name='Matrícula')),
                ('nombre', models.CharField(help_text='Nombre completo del alumno', max_length=100, verbose_name='Nombre completo')),
                ('calificaciones_texto', models.TextField(blank=True, default='', help_text='Escribe las calificaciones así: Materia:Nota, Materia:Nota', verbose_name='Calificaciones')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
            ],
            options={
                'verbose_name': 'Alumno',
                'verbose_name_plural': 'Alumnos',
                'ordering': ['matricula'],
            },
        ),
    ]
