# Generated by Django 6.0 on 2025-12-14 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='calificaciones_texto',
            field=models.TextField(blank=True, default='', help_text='Formato: Materia:Parcial1:Parcial2:Parcial3, ...', verbose_name='Calificaciones (P1:P2:P3)'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='matricula',
            field=models.CharField(max_length=20, unique=True, verbose_name='Matrícula'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre completo'),
        ),
    ]
