# Generated by Django 6.0 on 2025-12-15 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0002_alter_alumno_calificaciones_texto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='promedio_profesor',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Promedio adicional que el profesor asigna al alumno', max_digits=5, verbose_name='Promedio del profesor'),
        ),
    ]
