# Generated by Django 6.0 on 2025-12-15 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0003_alumno_promedio_profesor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='calificaciones_texto',
            field=models.TextField(blank=True, default='', help_text='Formato: Materia:Parcial1:Parcial2:Parcial3, ... (Escala 1-10)', verbose_name='Calificaciones (P1:P2:P3) - Escala 1-10'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='promedio_profesor',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Promedio adicional que el profesor asigna al alumno (Escala 1-10)', max_digits=4, verbose_name='Promedio del profesor (1-10)'),
        ),
    ]
