# Generated by Django 4.2.7 on 2025-12-16 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0005_alter_alumno_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterModelOptions(
            name='alumno',
            options={},
        ),
        migrations.AddField(
            model_name='alumno',
            name='grupo',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='alumno',
            name='primer_apellido',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='alumno',
            name='segundo_apellido',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='alumno',
            name='semestre',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='alumno',
            name='sexo',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='calificaciones_texto',
            field=models.TextField(blank=True, help_text='Formato: Materia:P1:P2:P3, ...', null=True),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='matricula',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='promedio_profesor',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Promedio adicional del profesor (1-10)', max_digits=4, null=True),
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semestre', models.CharField(blank=True, max_length=50, null=True)),
                ('p1', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('p2', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('p3', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='alumnos.alumno')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumnos.materia')),
            ],
            options={
                'unique_together': {('alumno', 'materia', 'semestre')},
            },
        ),
    ]
