# Generated by Django 4.2.7 on 2025-12-16 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0006_materia_alter_alumno_options_alumno_grupo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calificacion',
            options={'verbose_name_plural': 'Calificaciones'},
        ),
        migrations.AlterField(
            model_name='alumno',
            name='matricula',
            field=models.CharField(max_length=255, unique=True, verbose_name='Matrícula'),
        ),
    ]
