# Generated by Django 4.2.7 on 2025-12-16 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0008_alter_calificacion_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='promedio_final',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='alumno',
            name='promedio_primer_parcial',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='alumno',
            name='promedio_segundo_parcial',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='alumno',
            name='promedio_tercer_parcial',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
    ]
