# Generated by Django 4.2.7 on 2025-12-17 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0009_alumno_promedio_final_alumno_promedio_primer_parcial_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alumno',
            old_name='promedio_final',
            new_name='examen_final',
        ),
        migrations.RenameField(
            model_name='alumno',
            old_name='promedio_primer_parcial',
            new_name='prom_final_calculado',
        ),
        migrations.RenameField(
            model_name='alumno',
            old_name='promedio_segundo_parcial',
            new_name='prom_primer_parcial',
        ),
        migrations.RenameField(
            model_name='alumno',
            old_name='promedio_tercer_parcial',
            new_name='prom_segundo_parcial',
        ),
        migrations.AddField(
            model_name='alumno',
            name='prom_tercer_parcial',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
    ]
