# Generated by Django 4.2.7 on 2025-12-18 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0010_rename_promedio_final_alumno_examen_final_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='prom_primer_parcial',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='prom_segundo_parcial',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='prom_tercer_parcial',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
