# Generated by Django 4.2.7 on 2025-12-18 19:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0011_alter_alumno_prom_primer_parcial_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calificacion',
            options={'verbose_name_plural': 'Calificaciones'},
        ),
        migrations.RenameField(
            model_name='calificacion',
            old_name='promedio_semestral',
            new_name='examen_final',
        ),
        migrations.AlterUniqueTogether(
            name='calificacion',
            unique_together={('alumno', 'materia')},
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='examen_final',
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='prom_final_calculado',
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='prom_primer_parcial',
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='prom_segundo_parcial',
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='prom_tercer_parcial',
        ),
        migrations.AddField(
            model_name='alumno',
            name='carrera',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='promedio_parciales',
            field=models.DecimalField(blank=True, decimal_places=1, editable=False, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='materia',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='calificacion_final',
            field=models.DecimalField(blank=True, decimal_places=1, editable=False, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='calificacion',
            name='semestre',
        ),
    ]
